/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.SectionTree',
        'MyApp.view.SectionForm'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'section_tree',
                    id: 'section_tree',
                    minWidth: 250,
                    region: 'west',
                    split: true
                },
                {
                    xtype: 'container',
                    region: 'center',
                    id: 'main_container',
                    itemId: 'main_container',
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'section_form',
                            id: 'section_form',
                            itemId: 'section_form'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});