/*
 * File: app/view/TreeContextMenu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TreeContextMenu', {
    extend: 'Ext.menu.Menu',

    width: 120,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menuitem',
                    text: 'New',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Document'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var window = Ext.create("MyApp.view.NewSection",{
                                    }).show();
                                },
                                text: 'Section'
                            }
                        ],
                        listeners: {
                            beforeshow: {
                                fn: me.onMenuBeforeShow,
                                scope: me
                            }
                        }
                    }
                },
                {
                    xtype: 'menuseparator'
                },
                {
                    xtype: 'menuitem',
                    text: 'Disable'
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuBeforeShow: function(component, eOpts) {
        var tree = Ext.getCmp('section_tree');
        menuItems = this.items.items

        //hide the new document option if we are are in a section node
        if(tree.contextRecord.data.object_type == "Section"){
            component.items.items[0].setVisible(false);
        }
    }

});