/*
 * File: application/controller/ClientController.js
 * Date: Tue May 14 2013 12:31:11 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.ClientController', {
    extend: 'Ext.app.Controller',

    models: [
        'Client'
    ],
    stores: [
        'Client'
    ],
    views: [
        'ClientForm',
        'ClinetTab'
    ],

    init: function(application) {
        this.control({
            '[action=saveClient]': {
                click: this.saveClient
            },

            '[action=deleteClient]': {
                click: this.deleteClient
            },

            '#grid_client_menu': {
                itemclick: this.onClientGridMenuClick
            },

        });
    },

    saveClient: function() {
        var store_client = this.getStore("Client");
        var form = Ext.getCmp('form_client');

        var record = form.getForm().getRecord();

        if (form.getForm().isValid()) {

            form.setLoading(true);

            record.save({
                failure: function(record, operation) {
                    alert('TODO error management');
                },

                success: function(record, operation) {
                    form.getForm().updateRecord(record);
                },

                callback: function(record) {
                    form.setLoading(false);
                }
            });
        }
    },

    loadClient: function(record) {
        var store_clinet = this.getStore("Client");
        var form = Ext.getCmp('form_client');

        form.loadRecord(record);

    },

    deleteClient: function() {
        var store_client = this.getStore("Client");
        var form = Ext.getCmp('form_client');
        var record = form.getForm().getRecord();
        var desplay_name = record.data.name;

        Ext.MessageBox.show({
            title:'Confirm Deletion',
            msg: 'Are you sure you want to remove <b>' + desplay_name + '</b>?',
            buttons: Ext.Msg.YESNO,
            width:400,
            icon: Ext.window.MessageBox.QUESTION,
            fn: function(btn){
                if(btn == 'yes'){
                    store_client.remove(record);
                }
            }
        });
    },

    onClientGridMenuClick: function(view, record, item, index, e, eOpts) {
        var id = record.data.id;
        this.loadClient(record);
    }

});
