<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'config' => $baseDir . '/./',
    'Money' => $vendorDir . '/mathiasverraes/money/lib',
);
