/*
 * File: application/view/ABNField.js
 * Date: Sun May 05 2013 09:11:34 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ABNField', {
    extend: 'Ext.form.field.Text',
    alias: 'widget.abn_field',

    itemId: 'abn',
    fieldLabel: 'Australian Business Number (ABN)',
    name: 'abn',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                change: {
                    fn: me.onAbnChange,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onAbnChange: function(field, newValue, oldValue, eOpts) {
        //remove white space
        value = field.getValue().replace(/ /g,'');

        //format xx xxx xxx xxx
        value = value.substr(0,2) + (value.substr(2,3) != '' ? ' ' + value.substr(2,3) : "") + (value.substr(5,3) != '' ? ' ' + value.substr(5,3) : "") + (value.substr(8,3) != '' ? ' ' + value.substr(8,3) : "");

        field.setValue(value);
    },

    validator: function(value) {
        //To verify an ABN:
        //Subtract 1 from the first (left) digit to give a new eleven digit number
        //Multiply each of the digits in this new number by its weighting factor
        //Sum the resulting 11 products
        //Divide the total by 89, noting the remainder
        //If the remainder is zero the number is valid

        //ecample ABN: 53 004 085 616



        //remove white space
        value = value.replace(/ /g,'');

        //allow blank
        if(value == null || value == ''){
            return true;
        }

        if (value.length != 11 || isNaN(parseInt(value))){
            return "Invalid ABN number.";
        }

        var weighting = [10,1,3,5,7,9,11,13,15,17,19];
        var tally = (parseInt(value[0]) - 1) * weighting[0];

        for (var i = 1; i < value.length; i++){
            tally += (parseInt(value[i]) * weighting[i]);
        }

        if((tally % 89) == 0){
            return true; 
        }else{
            return "Invalid ABN number.";
        }


    }

});