/*
 * File: application/view/AccountCombo.js
 * Date: Thu May 16 2013 14:58:36 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AccountCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.account_combo',

    requires: [
        'MyApp.view.override.AccountCombo'
    ],

    groupField: 'account_type_id',
    selectOnFocus: true,
    editable: false,
    displayField: 'name',
    forceSelection: true,
    store: 'Account',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});