/*
 * File: application/view/AustralianDateField.js
 * Date: Tue May 14 2013 13:02:06 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AustralianDateField', {
    extend: 'Ext.form.field.Date',
    alias: 'widget.australiandatefield',

    altFormats: 'd/m/Y|d/m/y|d-m-y|d-m-Y|d/n/Y|d/n/y|d-n-y|d-n-Y|d/m|d-m|dm|dmy|dmY|d|j/m|j-m|jm|jmy|jmY|j|Y-m-d|j/n/y|j/n/Y|j/m/y|j/m/Y|j-n-y|j-n-Y|j-m-y|j-m-Y',
    format: 'd M Y',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});