/*
 * File: application/view/ClientComboBox.js
 * Date: Fri May 17 2013 15:14:06 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ClientComboBox', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.client_combobox',

    itemId: 'client_id',
    fieldLabel: 'Client',
    labelAlign: 'top',
    emptyText: 'Client Name',
    displayField: 'name',
    pageSize: 200,
    queryCaching: false,
    store: 'Client',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                beforequery: {
                    fn: me.onClient_idBeforeQuery,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onClient_idBeforeQuery: function(queryEvent, eOpts) {
        //this.store.clearFilter(true);
        //this.store.filter( { property: 'country_id', value: 2, exactMatch: true } );
    }

});