/*
 * File: application/view/ClientForm.js
 * Date: Thu May 09 2013 12:57:00 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ClientForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.client_form',

    requires: [
        'MyApp.view.ABNField',
        'MyApp.view.CountryComboBox'
    ],

    bodyPadding: 10,
    title: 'Details',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                labelAlign: 'top',
                msgTarget: 'side'
            },
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'id',
                    fieldLabel: 'Client ID',
                    name: 'id',
                    readOnly: true
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 1 0 0',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'name',
                                    fieldLabel: 'Name',
                                    name: 'name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'phone',
                                    fieldLabel: 'Phone Number',
                                    name: 'phone'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 0 0 1',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'abn_field',
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'email',
                                    afterLabelTextTpl: [
                                        '<img src="./images/help.png" alt="" width="16" height="16" class="help-tooltip pull-right">'
                                    ],
                                    fieldLabel: 'Email',
                                    name: 'email',
                                    vtype: 'email',
                                    vtypeText: 'Not a valid email address.'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: {
                        type: 'column'
                    },
                    title: 'Address',
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 1 0 0',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    flex: 1,
                                    height: 150,
                                    itemId: 'address',
                                    fieldLabel: 'Postal Address',
                                    name: 'address'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 0 0 1',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'country_combobox',
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'state',
                                    fieldLabel: 'State or Region',
                                    name: 'state'
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    itemId: 'postcode',
                                    fieldLabel: 'Postcode',
                                    name: 'postcode',
                                    hideTrigger: true,
                                    keyNavEnabled: false,
                                    mouseWheelEnabled: false,
                                    allowDecimals: false,
                                    minValue: 0
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            action: 'saveClient',
                            text: 'Save'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            action: 'deleteClient',
                            text: 'Delete'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});