/*
 * File: application/view/ClientTypeCombo.js
 * Date: Sun May 05 2013 10:15:48 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ClientTypeCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.client_type_combobox',

    fieldLabel: 'Client Type',
    labelAlign: 'top',
    msgTarget: 'side',
    name: 'client_type_id',
    allowBlank: false,
    emptyText: 'Type',
    editable: false,
    displayField: 'name',
    forceSelection: true,
    minChars: 1,
    store: 'ClientType',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});