/*
 * File: application/view/ContexSensitiveMenuItem.js
 * Date: Mon May 20 2013 15:54:46 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ContexSensitiveMenuItem', {
    extend: 'Ext.menu.Item',
    alias: 'widget.contex_sensitive_menu_item',

    text: 'Menu Item',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    },

    handler: function(item, e) {
        this.contextHandler(item,e);
    },

    contextVisibility: function(record) {
        return false;
    },

    contextText: function(record) {
        return this.text;
    },

    contextHandler: function(item, e) {

    }

});