/*
 * File: application/view/CountryComboBox.js
 * Date: Tue May 07 2013 18:11:05 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CountryComboBox', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.country_combobox',

    itemId: 'country_id',
    fieldLabel: 'Country',
    name: 'country_id',
    selectOnFocus: true,
    displayField: 'short_name',
    forceSelection: true,
    pageSize: 50,
    store: 'Country',
    typeAhead: true,
    valueField: 'id',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                beforerender: {
                    fn: me.onCountry_idBeforeRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onCountry_idBeforeRender: function(component, eOpts) {
        component.listConfig = {
            width:230,
            getInnerTpl: function() {
                return '<img src="./images/country-flags/{iso2}.png" alt="" width="16" height="11"> {short_name}';
            }
        }
    }

});