/*
 * File: application/view/InvoiceForm.js
 * Date: Thu May 16 2013 13:24:35 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.InvoiceForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.invoice_form',

    requires: [
        'MyApp.view.InvoiceStatusComboBox',
        'MyApp.view.ClientComboBox',
        'MyApp.view.AustralianDateField',
        'MyApp.view.InvoiceItemsGrid'
    ],

    autoScroll: true,
    bodyPadding: 10,
    title: 'Invoice (1234)',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                msgTarget: 'side'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            action: 'saveInvoice',
                            id: 'btn_save_invoice',
                            itemId: 'btn_save_invoice',
                            text: 'Save'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Make Payment'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Print',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Print'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Email'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            action: 'deleteInvoice',
                            text: 'Delete'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.6,
                            margin: 2,
                            width: 400,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    renderer: function(value, displayField) {
                                        var length = 5;
                                        var invoice_id = "" + value;

                                        while (invoice_id.length < length) {
                                            invoice_id = "0" + invoice_id;
                                        }

                                        return "INV-" + invoice_id;
                                    },
                                    flex: 1,
                                    itemId: 'id',
                                    fieldLabel: 'Tax Invoice Number',
                                    labelWidth: 130,
                                    name: 'id'
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'project_id',
                            fieldLabel: 'Label',
                            name: 'project_id'
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.4,
                            margin: 2,
                            width: 400,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    flex: 1,
                                    name: 'tax_includive',
                                    boxLabel: 'Amounts are tax inclusive',
                                    checked: true
                                },
                                {
                                    xtype: 'invoice_status_combobox',
                                    itemId: 'invoice_status_id',
                                    name: 'invoice_status_id',
                                    flex: 1
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: 2,
                            width: 400,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'client_combobox',
                                    name: 'client_id',
                                    inputId: 'client_id',
                                    flex: 1,
                                    listeners: {
                                        change: {
                                            fn: me.onClient_idChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    itemId: 'invoice_address',
                                    fieldLabel: 'Client Address',
                                    labelAlign: 'top',
                                    name: 'invoice_address'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: 2,
                            width: 400,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'australiandatefield',
                                    endDateField: 'due_date',
                                    itemId: 'issue_date',
                                    fieldLabel: 'Issued On',
                                    labelAlign: 'top',
                                    name: 'issue_date',
                                    inputId: 'issue_date',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    emptyText: 'Issue Date',
                                    vtype: 'daterange',
                                    flex: 1
                                },
                                {
                                    xtype: 'australiandatefield',
                                    startDateField: 'issue_date',
                                    itemId: 'due_date',
                                    fieldLabel: 'Due On',
                                    labelAlign: 'top',
                                    name: 'due_date',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    vtype: 'daterange',
                                    flex: 1
                                },
                                {
                                    xtype: 'australiandatefield',
                                    startDateField: 'issue_date',
                                    itemId: 'payed_date',
                                    fieldLabel: 'Payed On',
                                    labelAlign: 'top',
                                    name: 'payed_date',
                                    vtype: 'daterange',
                                    flex: 1
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'invoice_items_grid',
                    itemId: 'grid_invoice_items'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'textareafield',
                            columnWidth: 0.6,
                            height: 75,
                            itemId: 'note',
                            fieldLabel: 'Note to customer',
                            labelAlign: 'top',
                            name: 'note'
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.4,
                            id: 'invoice_totals',
                            margin: 2,
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    id: 'fld_invoice_subtotal',
                                    itemId: 'fld_invoice_subtotal',
                                    fieldLabel: 'Subtotal'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'fld_invoice_tax',
                                    itemId: 'fld_invoice_tax',
                                    fieldLabel: 'Tax'
                                },
                                {
                                    xtype: 'displayfield',
                                    id: 'fld_invoice_total',
                                    itemId: 'field_total',
                                    fieldLabel: 'Total'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    id: 'project_id',
                                    itemId: 'project_id',
                                    fieldLabel: 'Label'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onClient_idChange: function(field, newValue, oldValue, eOpts) {
        //var client = field.getStore().getById(newValue).data;
        //field.up('form').getForm().findField('invoice_address').setValue(client.address);


    }

});