/*
 * File: application/view/InvoiceStatusComboBox.js
 * Date: Wed May 08 2013 17:20:33 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.InvoiceStatusComboBox', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.invoice_status_combobox',

    fieldLabel: 'Status',
    labelAlign: 'top',
    allowBlank: false,
    allowOnlyWhitespace: false,
    displayField: 'name',
    forceSelection: true,
    store: 'InvoiceStatus',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                beforerender: {
                    fn: me.onInvoice_status_idBeforeRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onInvoice_status_idBeforeRender: function(component, eOpts) {
        component.listConfig = {
            width:230,
            getInnerTpl: function() {
                return '<div class="x-combo-title">{name}</div><div class="x-combo-description">{description}</div>';
            }
        }
    }

});