/*
 * File: application/view/MyContainer5.js
 * Date: Wed May 01 2013 17:51:50 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer5', {
    extend: 'Ext.container.Container',

    requires: [
        'MyApp.view.ClientComboBox',
        'MyApp.view.AustralianDateField'
    ],

    layout: {
        type: 'column'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    columnWidth: 0.5,
                    margin: 2,
                    width: 400,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'ClientComboBox',
                            flex: 1
                        },
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            fieldLabel: 'Client Address'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    columnWidth: 0.5,
                    margin: 2,
                    width: 400,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Invoice Id'
                        },
                        {
                            xtype: 'australiandatefield',
                            endDateField: 'due_date',
                            id: 'issue_date2',
                            fieldLabel: 'Issue Date',
                            name: 'issue_date',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            emptyText: 'Issue Date',
                            vtype: 'daterange',
                            flex: 1
                        },
                        {
                            xtype: 'australiandatefield',
                            startDateField: 'issue_date',
                            id: 'due_date2',
                            fieldLabel: 'Due Date',
                            name: 'due_date',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            vtype: 'daterange',
                            flex: 1
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});