/*
 * File: application/view/MyColumn6.js
 * Date: Tue Apr 23 2013 17:14:27 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyColumn6', {
    extend: 'Ext.grid.column.Column',
    alias: 'widget.mycolumn6',

    summaryType: 'sum',
    cls: 'row-total',
    maxWidth: 100,
    minWidth: 50,
    width: 100,
    resizable: false,
    text: 'Total',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    },

    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
        console.log(record.data);
        metaData.css = 'cell-total';

        var total = (record.data.price * record.data.qty);
        return Ext.util.Format.number(total, '$0,000.00');
    }

});