/*
 * File: application/view/MyForm6.js
 * Date: Tue Apr 30 2013 21:01:28 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyForm6', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform6',

    bodyPadding: 10,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                labelAlign: 'top',
                msgTarget: 'side'
            },
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'id',
                    fieldLabel: 'ID'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'name',
                    fieldLabel: 'Name'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    itemId: 'description',
                    fieldLabel: 'Description'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 1 0 0',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'retail_price',
                                    fieldLabel: 'Retail Price'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    itemId: 'purchase_account_id',
                                    fieldLabel: 'Purchase Account'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    itemId: 'tax_rate_id',
                                    fieldLabel: 'Tax Rate'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 0 0 1',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'wholesale_proce',
                                    fieldLabel: 'Wholesale Price'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    itemId: 'sales_account_id',
                                    fieldLabel: 'Sales Account'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'unit_of_measurement',
                                    fieldLabel: 'Unit of mesasurement'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});