/*
 * File: application/view/MyGridPanel1.js
 * Date: Tue Apr 30 2013 16:29:13 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyGridPanel1', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mygridpanel1',

    requires: [
        'MyApp.view.ClearTriggerField'
    ],

    autoRender: false,
    maxWidth: 450,
    minWidth: 150,
    width: 250,
    bodyBorder: false,
    animCollapse: false,
    collapsed: false,
    collapsible: true,
    hideCollapseTool: true,
    titleCollapse: true,
    allowDeselect: true,
    columnLines: false,
    forceFit: true,
    hideHeaders: true,
    store: 'Product',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'cleartrigger'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            icon: '/images/settings.png'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '<img class="pull-left menu-image" src="/images/32/product.png"><div class="menu-name">{id} - {name}</div><div class="menu-description">{description}</div>'
                    ],
                    dataIndex: 'id'
                }
            ],
            selModel: Ext.create('Ext.selection.RowModel', {

            }),
            plugins: [
                Ext.create('Ext.grid.plugin.BufferedRenderer', {

                })
            ]
        });

        me.callParent(arguments);
    }

});