/*
 * File: application/view/NewItemMenu.js
 * Date: Mon May 20 2013 13:27:27 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.NewItemMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.new_item_menu',

    width: 150,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menuitem',
                    handler: function(item, e) {
                        var x = Ext.create("MyApp.view.NewClient",{
                        }).show();
                    },
                    icon: '/images/16/individual.png',
                    text: 'Add Client'
                },
                {
                    xtype: 'menuitem',
                    handler: function(item, e) {
                        var x = Ext.create("MyApp.view.NewFolder",{
                        }).show();
                    },
                    icon: '/images/16/project.png',
                    text: 'Add Folder'
                },
                {
                    xtype: 'menuitem',
                    handler: function(item, e) {
                        var x = Ext.create("MyApp.view.NewInvoice",{
                        }).show();
                    },
                    icon: '/images/16/invoice.png',
                    text: 'Create Incoice'
                }
            ],
            listeners: {
                beforeshow: {
                    fn: me.onMenuBeforeShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onMenuBeforeShow: function(component, eOpts) {
        //check to see what to show
    },

    filterMenu: function(record) {

    }

});