/*
 * File: application/view/ProductForm.js
 * Date: Thu May 16 2013 13:22:12 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ProductForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.product_form',

    requires: [
        'MyApp.view.TaxRateCombo',
        'MyApp.view.AccountCombo'
    ],

    autoScroll: true,
    bodyPadding: 10,
    title: 'Product',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                labelAlign: 'top',
                msgTarget: 'side'
            },
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'id',
                    fieldLabel: 'ID',
                    name: 'id',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'name',
                    fieldLabel: 'Name',
                    name: 'name',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    maxLength: 100,
                    minLength: 2
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    itemId: 'description',
                    fieldLabel: 'Description',
                    name: 'description',
                    maxLength: 250
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'column'
                    },
                    items: [
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 1 0 0',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    itemId: 'retail_price',
                                    fieldLabel: 'Retail Price',
                                    name: 'retail_price',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    itemId: 'wholesale_proce',
                                    fieldLabel: 'Wholesale Price',
                                    name: 'wholesale_price',
                                    autoStripChars: true
                                },
                                {
                                    xtype: 'tax_rate_combo',
                                    itemId: 'tax_rate_id',
                                    fieldLabel: 'Tax Rate',
                                    name: 'tax_rate_id',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    selectOnFocus: true,
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            columnWidth: 0.5,
                            margin: '0 0 0 1',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'account_combo',
                                    itemId: 'sales_account_id',
                                    fieldLabel: 'Sales Account',
                                    name: 'sales_account_id',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    flex: 1
                                },
                                {
                                    xtype: 'account_combo',
                                    itemId: 'purchase_account_id',
                                    fieldLabel: 'Purchase Account',
                                    name: 'purchase_account_id',
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'unit_of_measurement',
                                    fieldLabel: 'Unit of mesasurement',
                                    name: 'unit_of_measurement'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            action: 'saveProduct',
                            text: 'Save'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            action: 'deleteProduct',
                            id: 'btn_product_delete',
                            text: 'Delete'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});