/*
 * File: application/model/Account.js
 * Date: Tue May 07 2013 17:12:46 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Account', {
    extend: 'Ext.data.Model',

    uses: [
        'MyApp.model.InvoiceItem'
    ],

    fields: [
        {
            mapping: 'id',
            name: 'id',
            type: 'int',
            useNull: true
        },
        {
            name: 'number',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'account_type_id',
            type: 'int'
        },
        {
            name: 'tax_rate_id',
            type: 'int'
        },
        {
            name: 'actice',
            type: 'boolean'
        },
        {
            name: 'editable',
            type: 'boolean'
        }
    ],

    proxy: {
        type: 'ajax',
        url: '/api/account/',
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    belongsTo: {
        model: 'MyApp.model.InvoiceItem',
        primaryKey: 'sales_account_id',
        foreignKey: 'id'
    }
});