/*
 * File: application/model/Country.js
 * Date: Tue May 07 2013 17:12:46 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Country', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'short_name'
        },
        {
            name: 'long_name'
        },
        {
            name: 'number_code'
        },
        {
            name: 'iso2'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/api/country/',
        reader: {
            type: 'json',
            root: 'data'
        }
    }
});