/*
 * File: application/model/InvoiceItem.js
 * Date: Tue May 07 2013 17:12:46 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.InvoiceItem', {
    extend: 'Ext.data.Model',
    alias: 'model.InvoiceItem',

    uses: [
        'MyApp.model.Account'
    ],

    fields: [
        {
            name: 'id',
            type: 'int',
            useNull: true
        },
        {
            mapping: 'product_id',
            name: 'product_id',
            type: 'int',
            useNull: true
        },
        {
            name: 'description',
            type: 'string',
            useNull: true
        },
        {
            name: 'retail_price',
            type: 'float',
            useNull: true
        },
        {
            name: 'sales_account_id',
            useNull: true
        },
        {
            name: 'qty',
            type: 'float',
            useNull: true
        },
        {
            name: 'tax_rate_id',
            useNull: true
        },
        {
            name: 'invoice_id'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/api/invoice_item/',
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    hasOne: {
        model: 'MyApp.model.Account',
        foreignKey: 'sales_account_id'
    },

    validations: [
        {
            type: 'presence',
            field: 'description'
        },
        {
            type: 'presence',
            field: 'sales_account_id'
        },
        {
            type: 'presence',
            field: 'retail_price'
        },
        {
            type: 'presence',
            field: 'qty'
        },
        {
            type: 'presence',
            field: 'tax_rate_id'
        }
    ]
});