/*
 * File: application/model/InvoiceStatus.js
 * Date: Wed May 08 2013 13:07:03 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.InvoiceStatus', {
    extend: 'Ext.data.Model',

    uses: [
        'MyApp.model.Invoice'
    ],

    fields: [
        {
            mapping: 'id',
            name: 'id',
            type: 'int'
        },
        {
            mapping: 'name',
            name: 'name',
            type: 'string'
        },
        {
            name: 'description'
        }
    ],

    belongsTo: {
        model: 'MyApp.model.Invoice',
        primaryKey: 'invoice_status_id',
        foreignKey: 'id'
    },

    proxy: {
        type: 'rest',
        noCache: false,
        url: '/api/invoice_status',
        reader: {
            type: 'json',
            root: 'data'
        }
    }
});