/*
 * File: application/store/ProjectTree.js
 * Date: Fri May 17 2013 14:25:15 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ProjectTree', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.Tree'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.Tree',
            storeId: 'ProjectTreeStore',
            proxy: {
                type: 'ajax',
                url: '/structured_api/project_tree/',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});