/*
 * File: application/store/TaxRate.js
 * Date: Wed May 01 2013 17:51:50 GMT+1000 (EST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TaxRate', {
    extend: 'Ext.data.Store',
    alias: 'store.TaxRate',

    requires: [
        'MyApp.model.TaxRate'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.TaxRate',
            storeId: 'TaxRate'
        }, cfg)]);
    }
});